### ISSUE TITLE
RR interval duplication in printing.

### ISSUE THREAD

**Issue by HufflyCodes** [fsmeraldi/bleakheart#2]
Great work on this bit of software, I have only been going through this off and on for a couple days now, and I have never submitted an issue before. But I was looking over your examples to adapt your software and add some features of my own but I came across one small error when using your Heart rate callback example.

when processing your RR intervals on line 165 in bleakheart.py it is currently:
 
`rr = int.from_bytes(data[offset:offset+2],
                                    'little', signed=False)`

Where it never gets the next value in the array. A simple fix would be:

`rr = int.from_bytes(data[i:i+2],
                                    'little', signed=False)`

**Comment by fsmeraldi** [comment]
Well spotted, thank you very much! I'll fix it and update the release. Glad you find the software useful.

**Comment by fsmeraldi** [comment]
Fixed in version 0.1.1 - you are officially the first contributor! Thanks again.
I recommend you also update bleak to version 0.21.1 if you have not done it yet - it reduces the delay in starting ECG notifications and seems to improve MacOS compatibility.

**Comment by HufflyCodes** [comment]
Interesting you mention that I have noticed that on Windows 10 it does take about 30 seconds for ECG data to roll in similar to the other post. I don't think it's an issue in BleakHeart however; I am pretty sure it's something with how windows deals with BT from what I have been reading. I plan on shifting this to an RPi eventually so I don't foresee any issues there, that and the unix timestamp helps deal with any potential initial delays.

**Comment by fsmeraldi** [comment]
I had exactly the same issue on Linux with the previous version of Bleak, and the upgrade solved it. I have not tried regressing to the older version, so it is in fact possible that some other library got upgraded in the meanwhile, I cannot say.
